// This file is auto-generated by @hey-api/openapi-ts

export const def_0Schema = {
  type: 'object',
  properties: {
    authorization: {
      type: 'string',
      example: 'Bearer 123',
    },
  },
  required: ['authorization'],
  title: 'authSchema',
} as const;

export const def_1Schema = {
  type: 'object',
  properties: {
    statusCode: {
      type: 'string',
    },
    error: {
      type: 'string',
    },
    message: {
      type: 'string',
    },
  },
  required: ['statusCode', 'error', 'message'],
  title: 'errorSchema',
} as const;
