// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type {
  CreateAssetData,
  CreateAssetErrors,
  CreateAssetResponses,
  CreateItemData,
  CreateItemErrors,
  CreateItemResponses,
  CreateWebhookData,
  CreateWebhookErrors,
  CreateWebhookResponses,
  DeleteAssetData,
  DeleteAssetErrors,
  DeleteAssetResponses,
  DeleteItemsData,
  DeleteItemsErrors,
  DeleteItemsResponses,
  DeletePublicFileData,
  DeletePublicFileErrors,
  DeletePublicFileResponses,
  DeleteWebhookData,
  DeleteWebhookErrors,
  DeleteWebhookResponses,
  GetAssetData,
  GetAssetErrors,
  GetAssetResponses,
  GetCollectionData,
  GetCollectionErrors,
  GetCollectionResponses,
  GetComponentData,
  GetComponentErrors,
  GetComponentResponses,
  GetFormData,
  GetFormErrors,
  GetFormResponses,
  GetFormSubmissionData,
  GetFormSubmissionErrors,
  GetFormSubmissionResponses,
  GetItemData,
  GetItemErrors,
  GetItemResponses,
  GetPageData,
  GetPageErrors,
  GetPageResponses,
  GetPublicFileData,
  GetPublicFileErrors,
  GetPublicFileResponses,
  GetSiteData,
  GetSiteErrors,
  GetSiteResponses,
  GetWebhookData,
  GetWebhookErrors,
  GetWebhookResponses,
  ListAssetsData,
  ListAssetsErrors,
  ListAssetsResponses,
  ListCollectionsData,
  ListCollectionsErrors,
  ListCollectionsResponses,
  ListComponentsData,
  ListComponentsErrors,
  ListComponentsResponses,
  ListFormsData,
  ListFormsErrors,
  ListFormsResponses,
  ListFormSubmissionsData,
  ListFormSubmissionsErrors,
  ListFormSubmissionsResponses,
  ListItemsData,
  ListItemsErrors,
  ListItemsResponses,
  ListPagesData,
  ListPagesErrors,
  ListPagesResponses,
  ListPublicFilesData,
  ListPublicFilesErrors,
  ListPublicFilesResponses,
  ListRedirectsData,
  ListRedirectsErrors,
  ListRedirectsResponses,
  ListSitesData,
  ListSitesErrors,
  ListSitesResponses,
  ListWebhooksData,
  ListWebhooksErrors,
  ListWebhooksResponses,
  PublishSiteData,
  PublishSiteErrors,
  PublishSiteResponses,
  UpdateAssetData,
  UpdateAssetErrors,
  UpdateAssetResponses,
  UpdateItemData,
  UpdateItemErrors,
  UpdateItemResponses,
  UpdatePublicFileData,
  UpdatePublicFileErrors,
  UpdatePublicFileResponses,
} from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<
  TData,
  ThrowOnError
> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export class Sites {
  /**
   * List of all sites
   */
  public static list<ThrowOnError extends boolean = false>(options?: Options<ListSitesData, ThrowOnError>) {
    return (options?.client ?? client).get<ListSitesResponses, ListSitesErrors, ThrowOnError>({
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/sites',
      ...options,
    });
  }

  /**
   * Get details of a site.
   */
  public static get<ThrowOnError extends boolean = false>(options: Options<GetSiteData, ThrowOnError>) {
    return (options.client ?? client).get<GetSiteResponses, GetSiteErrors, ThrowOnError>({
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/sites/{siteId}',
      ...options,
    });
  }

  /**
   * Publish a site
   */
  public static publish<ThrowOnError extends boolean = false>(options: Options<PublishSiteData, ThrowOnError>) {
    return (options.client ?? client).post<PublishSiteResponses, PublishSiteErrors, ThrowOnError>({
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/sites/{siteId}/publish',
      ...options,
    });
  }
}

export class Pages {
  /**
   * List of pages in a site
   */
  public static list<ThrowOnError extends boolean = false>(options: Options<ListPagesData, ThrowOnError>) {
    return (options.client ?? client).get<ListPagesResponses, ListPagesErrors, ThrowOnError>({
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/sites/{siteId}/pages',
      ...options,
    });
  }

  /**
   * Get page data
   */
  public static get<ThrowOnError extends boolean = false>(options: Options<GetPageData, ThrowOnError>) {
    return (options.client ?? client).get<GetPageResponses, GetPageErrors, ThrowOnError>({
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/sites/{siteId}/pages/{pageId}',
      ...options,
    });
  }
}

export class Components {
  /**
   * List of components in a site
   */
  public static list<ThrowOnError extends boolean = false>(options: Options<ListComponentsData, ThrowOnError>) {
    return (options.client ?? client).get<ListComponentsResponses, ListComponentsErrors, ThrowOnError>({
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/sites/{siteId}/components',
      ...options,
    });
  }

  /**
   * Get Component
   *
   * Get a component from a site by its id
   */
  public static get<ThrowOnError extends boolean = false>(options: Options<GetComponentData, ThrowOnError>) {
    return (options.client ?? client).get<GetComponentResponses, GetComponentErrors, ThrowOnError>({
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/sites/{siteId}/components/{componentId}',
      ...options,
    });
  }
}

export class Assets {
  /**
   * Delete Asset
   */
  public static delete<ThrowOnError extends boolean = false>(options: Options<DeleteAssetData, ThrowOnError>) {
    return (options.client ?? client).delete<DeleteAssetResponses, DeleteAssetErrors, ThrowOnError>({
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/assets/{assetId}',
      ...options,
    });
  }

  /**
   * Get Asset
   *
   * Get an asset by its id
   */
  public static get<ThrowOnError extends boolean = false>(options: Options<GetAssetData, ThrowOnError>) {
    return (options.client ?? client).get<GetAssetResponses, GetAssetErrors, ThrowOnError>({
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/assets/{assetId}',
      ...options,
    });
  }

  /**
   * Update an asset
   */
  public static update<ThrowOnError extends boolean = false>(options: Options<UpdateAssetData, ThrowOnError>) {
    return (options.client ?? client).patch<UpdateAssetResponses, UpdateAssetErrors, ThrowOnError>({
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/assets/{assetId}',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }

  /**
   * List Assets
   *
   * List of all assets in a workspace
   */
  public static list<ThrowOnError extends boolean = false>(options: Options<ListAssetsData, ThrowOnError>) {
    return (options.client ?? client).get<ListAssetsResponses, ListAssetsErrors, ThrowOnError>({
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/workspaces/{workspaceId}/assets',
      ...options,
    });
  }

  /**
   * Create Asset
   *
   * Create an asset in a workspace
   */
  public static create<ThrowOnError extends boolean = false>(options: Options<CreateAssetData, ThrowOnError>) {
    return (options.client ?? client).post<CreateAssetResponses, CreateAssetErrors, ThrowOnError>({
      ...formDataBodySerializer,
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/workspaces/{workspaceId}/assets',
      ...options,
      headers: {
        'Content-Type': null,
        ...options.headers,
      },
    });
  }
}

export class Forms {
  /**
   * List of all forms in a site
   */
  public static list<ThrowOnError extends boolean = false>(options: Options<ListFormsData, ThrowOnError>) {
    return (options.client ?? client).get<ListFormsResponses, ListFormsErrors, ThrowOnError>({
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/sites/{siteId}/forms',
      ...options,
    });
  }

  /**
   * Get form by form ID
   */
  public static get<ThrowOnError extends boolean = false>(options: Options<GetFormData, ThrowOnError>) {
    return (options.client ?? client).get<GetFormResponses, GetFormErrors, ThrowOnError>({
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/forms/{formId}',
      ...options,
    });
  }
}

export class FormSubmissions {
  /**
   * List form submissions by form ID
   */
  public static list<ThrowOnError extends boolean = false>(options: Options<ListFormSubmissionsData, ThrowOnError>) {
    return (options.client ?? client).get<ListFormSubmissionsResponses, ListFormSubmissionsErrors, ThrowOnError>({
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/forms/{formId}/submissions',
      ...options,
    });
  }

  /**
   * Form submission by form submission ID
   */
  public static get<ThrowOnError extends boolean = false>(options: Options<GetFormSubmissionData, ThrowOnError>) {
    return (options.client ?? client).get<GetFormSubmissionResponses, GetFormSubmissionErrors, ThrowOnError>({
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/form_submissions/{formSubmissionId}',
      ...options,
    });
  }
}

export class Collections {
  /**
   * List of all collections in a given site
   */
  public static list<ThrowOnError extends boolean = false>(options: Options<ListCollectionsData, ThrowOnError>) {
    return (options.client ?? client).get<ListCollectionsResponses, ListCollectionsErrors, ThrowOnError>({
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/sites/{siteId}/collections',
      ...options,
    });
  }

  /**
   * Get a collection
   */
  public static get<ThrowOnError extends boolean = false>(options: Options<GetCollectionData, ThrowOnError>) {
    return (options.client ?? client).get<GetCollectionResponses, GetCollectionErrors, ThrowOnError>({
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/collections/{collectionId}',
      ...options,
    });
  }
}

export class Items {
  /**
   * Delete items in a collection
   */
  public static delete<ThrowOnError extends boolean = false>(options: Options<DeleteItemsData, ThrowOnError>) {
    return (options.client ?? client).delete<DeleteItemsResponses, DeleteItemsErrors, ThrowOnError>({
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/collections/{collectionId}/items',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }

  /**
   * List of items in a collection
   */
  public static list<ThrowOnError extends boolean = false>(options: Options<ListItemsData, ThrowOnError>) {
    return (options.client ?? client).get<ListItemsResponses, ListItemsErrors, ThrowOnError>({
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/collections/{collectionId}/items',
      ...options,
    });
  }

  /**
   * Create an item in a collection
   */
  public static create<ThrowOnError extends boolean = false>(options: Options<CreateItemData, ThrowOnError>) {
    return (options.client ?? client).post<CreateItemResponses, CreateItemErrors, ThrowOnError>({
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/collections/{collectionId}/items',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }

  /**
   * Get an item in a collection
   */
  public static get<ThrowOnError extends boolean = false>(options: Options<GetItemData, ThrowOnError>) {
    return (options.client ?? client).get<GetItemResponses, GetItemErrors, ThrowOnError>({
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/collections/{collectionId}/items/{itemId}',
      ...options,
    });
  }

  /**
   * Update an item in a collection
   */
  public static update<ThrowOnError extends boolean = false>(options: Options<UpdateItemData, ThrowOnError>) {
    return (options.client ?? client).patch<UpdateItemResponses, UpdateItemErrors, ThrowOnError>({
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/collections/{collectionId}/items/{itemId}',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }
}

export class PublicFiles {
  /**
   * List of public files in a site
   */
  public static list<ThrowOnError extends boolean = false>(options: Options<ListPublicFilesData, ThrowOnError>) {
    return (options.client ?? client).get<ListPublicFilesResponses, ListPublicFilesErrors, ThrowOnError>({
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/sites/{siteId}/public_files',
      ...options,
    });
  }

  /**
   * Delete public file
   */
  public static delete<ThrowOnError extends boolean = false>(options: Options<DeletePublicFileData, ThrowOnError>) {
    return (options.client ?? client).delete<DeletePublicFileResponses, DeletePublicFileErrors, ThrowOnError>({
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/sites/{siteId}/public_files/{path}',
      ...options,
    });
  }

  /**
   * Get public file
   */
  public static get<ThrowOnError extends boolean = false>(options: Options<GetPublicFileData, ThrowOnError>) {
    return (options.client ?? client).get<GetPublicFileResponses, GetPublicFileErrors, ThrowOnError>({
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/sites/{siteId}/public_files/{path}',
      ...options,
    });
  }

  /**
   * Update public file
   */
  public static update<ThrowOnError extends boolean = false>(options: Options<UpdatePublicFileData, ThrowOnError>) {
    return (options.client ?? client).patch<UpdatePublicFileResponses, UpdatePublicFileErrors, ThrowOnError>({
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/sites/{siteId}/public_files/{path}',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }
}

export class Redirects {
  /**
   * List of redirects in a site
   */
  public static list<ThrowOnError extends boolean = false>(options: Options<ListRedirectsData, ThrowOnError>) {
    return (options.client ?? client).get<ListRedirectsResponses, ListRedirectsErrors, ThrowOnError>({
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/sites/{siteId}/redirects',
      ...options,
    });
  }
}

export class Webhooks {
  /**
   * List all webhooks by site ID
   */
  public static list<ThrowOnError extends boolean = false>(options: Options<ListWebhooksData, ThrowOnError>) {
    return (options.client ?? client).get<ListWebhooksResponses, ListWebhooksErrors, ThrowOnError>({
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/sites/{siteId}/webhooks',
      ...options,
    });
  }

  /**
   * Create webhook
   */
  public static create<ThrowOnError extends boolean = false>(options: Options<CreateWebhookData, ThrowOnError>) {
    return (options.client ?? client).post<CreateWebhookResponses, CreateWebhookErrors, ThrowOnError>({
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/sites/{siteId}/webhooks',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }

  /**
   * Delete a webhook by ID
   */
  public static delete<ThrowOnError extends boolean = false>(options: Options<DeleteWebhookData, ThrowOnError>) {
    return (options.client ?? client).delete<DeleteWebhookResponses, DeleteWebhookErrors, ThrowOnError>({
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/webhooks/{webhookId}',
      ...options,
    });
  }

  /**
   * Get a webhook by ID
   */
  public static get<ThrowOnError extends boolean = false>(options: Options<GetWebhookData, ThrowOnError>) {
    return (options.client ?? client).get<GetWebhookResponses, GetWebhookErrors, ThrowOnError>({
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/webhooks/{webhookId}',
      ...options,
    });
  }
}
