// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'https://api.versoly.com/v1' | (string & {});
};

/**
 * authSchema
 */
export type Def0 = {
  authorization: string;
};

/**
 * errorSchema
 */
export type Def1 = {
  type?: string;
  status: number;
  title?: string;
  detail?: string;
  instance?: string;
};

/**
 * errors/schemas/bad-request
 */
export type Def2 = {
  type: 'about:blank';
  status: 400;
  title: 'Bad Request';
  detail?: string;
  instance?: string;
};

/**
 * errors/schemas/unauthorized
 */
export type Def3 = {
  type: 'about:blank';
  status: 401;
  title: 'Unauthorized';
  detail?: string;
  instance?: string;
};

/**
 * errors/schemas/not-found
 */
export type Def4 = {
  type: 'about:blank';
  status: 404;
  title: 'Not Found';
  detail?: string;
  instance?: string;
};

/**
 * errors/schemas/conflict
 */
export type Def5 = {
  type: 'about:blank';
  status: 409;
  title: 'Conflict';
  detail?: string;
  instance?: string;
};

/**
 * errors/schemas/too-many-requests
 */
export type Def6 = {
  type: 'about:blank';
  status: 429;
  title: 'Too Many Requests';
  detail?: string;
  instance?: string;
};

/**
 * errors/schemas/internal-server-error
 */
export type Def7 = {
  type: 'about:blank';
  status: 500;
  title: 'Internal Server Error';
  detail?: string;
  instance?: string;
};

export type ListSitesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/sites';
};

export type ListSitesErrors = {
  /**
   * Default Response
   */
  400: Def2;
  /**
   * Default Response
   */
  401: Def3;
  /**
   * Default Response
   */
  404: Def4;
  /**
   * Default Response
   */
  409: Def5;
  /**
   * Default Response
   */
  429: Def6;
  /**
   * Default Response
   */
  500: Def7;
  /**
   * Default Response
   */
  '4XX': Def1;
};

export type ListSitesError = ListSitesErrors[keyof ListSitesErrors];

export type ListSitesResponses = {
  /**
   * Default Response
   */
  200: {
    data: Array<{
      id: string;
      name: string;
      workspaceId: string;
      createdAt: string;
      publishedAt?: string;
      updatedAt: string;
    }>;
  };
};

export type ListSitesResponse = ListSitesResponses[keyof ListSitesResponses];

export type GetSiteData = {
  body?: never;
  path: {
    /**
     * Unique identifier for the Site
     */
    siteId: string;
  };
  query?: never;
  url: '/sites/{siteId}';
};

export type GetSiteErrors = {
  /**
   * Default Response
   */
  400: Def2;
  /**
   * Default Response
   */
  401: Def3;
  /**
   * Default Response
   */
  404: Def4;
  /**
   * Default Response
   */
  409: Def5;
  /**
   * Default Response
   */
  429: Def6;
  /**
   * Default Response
   */
  500: Def7;
  /**
   * Default Response
   */
  '4XX': Def1;
};

export type GetSiteError = GetSiteErrors[keyof GetSiteErrors];

export type GetSiteResponses = {
  /**
   * Default Response
   */
  200: {
    id: string;
    name: string;
    customDomain: string | null;
    planId: string;
    workspaceId: string;
    sitePassword: string | null;
    seo: {
      title: string;
      description: string;
    };
    metaTags: Array<{
      field: string;
      value: string;
      content: string;
    }>;
    favicon: string | null;
    baseUrl: string | null;
    analytics: boolean;
    integrations: {
      [key: string]: {
        id: string;
        delay: number;
      };
    };
    head: string;
    scripts: string;
    config: {
      [key: string]: unknown;
    };
    CSS: string;
    JS: string;
    files: {
      _redirects: string;
      'sitemap.xml': string;
      'page-sitemap.xml': string;
    };
    folders: Array<{
      id: string;
      name: string;
      slug: string;
    }>;
    componentFolders: Array<{
      id: string;
      name: string;
    }>;
    collectionVariables: {
      collections: {
        [key: string]: {
          name: string;
          singularName: string;
          offset: number;
          limit: number;
          sortItems?: Array<{
            fieldName: string;
            sortBy: 'asc' | 'desc';
          }>;
          filterItems?: Array<{
            fieldName: string;
            filterType: '<' | '>' | '<=' | '>=' | '==' | '!=';
            value?: string;
          }>;
        };
      };
    };
    createdAt: string;
    updatedAt: string;
    publishedAt?: string;
  };
};

export type GetSiteResponse = GetSiteResponses[keyof GetSiteResponses];

export type PublishSiteData = {
  body?: never;
  path: {
    /**
     * Unique identifier for the Site
     */
    siteId: string;
  };
  query?: never;
  url: '/sites/{siteId}/publish';
};

export type PublishSiteErrors = {
  /**
   * Default Response
   */
  400: Def2;
  /**
   * Default Response
   */
  401: Def3;
  /**
   * Default Response
   */
  404: Def4;
  /**
   * Default Response
   */
  409: Def5;
  /**
   * Default Response
   */
  429: Def6;
  /**
   * Default Response
   */
  500: Def7;
  /**
   * Default Response
   */
  '4XX': Def1;
};

export type PublishSiteError = PublishSiteErrors[keyof PublishSiteErrors];

export type PublishSiteResponses = {
  /**
   * Successfully executed
   */
  204: void;
};

export type PublishSiteResponse = PublishSiteResponses[keyof PublishSiteResponses];

export type ListPagesData = {
  body?: never;
  path: {
    /**
     * Unique identifier for the Site
     */
    siteId: string;
  };
  query?: never;
  url: '/sites/{siteId}/pages';
};

export type ListPagesErrors = {
  /**
   * Default Response
   */
  400: Def2;
  /**
   * Default Response
   */
  401: Def3;
  /**
   * Default Response
   */
  404: Def4;
  /**
   * Default Response
   */
  409: Def5;
  /**
   * Default Response
   */
  429: Def6;
  /**
   * Default Response
   */
  500: Def7;
  /**
   * Default Response
   */
  '4XX': Def1;
};

export type ListPagesError = ListPagesErrors[keyof ListPagesErrors];

export type ListPagesResponses = {
  /**
   * Default Response
   */
  200: {
    data: Array<{
      id: string;
      name: string;
      slug: string;
      folderId: string | null;
      folderPath?: string;
      status: 'draft' | 'publish';
      head: string;
      scripts: string;
      seo: {
        title: string;
        description: string;
      };
      metaTags: Array<{
        field: string;
        value: string;
        content: string;
      }>;
      layout: {
        name: string | null;
      };
      bodyProperties: {
        id?: string;
        className?: string;
        [key: string]: string | undefined;
      };
      content: string;
      collectionProperties?: {
        name: string;
        groupBy: string | null;
        pageType: 'list' | 'detail';
        offset: number;
        limit: number;
        itemsPerPage: number | null;
        filterItems: Array<{
          fieldName: string;
          filterType: '<' | '>' | '<=' | '>=' | '==' | '!=';
          value?: string;
        }>;
        sortItems: Array<{
          fieldName: string;
          sortBy: 'asc' | 'desc';
        }>;
      };
      createdAt: string;
      updatedAt: string;
      deletedAt?: string;
      createdBy: string;
      updatedBy: string;
      deletedBy?: string;
    }>;
  };
};

export type ListPagesResponse = ListPagesResponses[keyof ListPagesResponses];

export type GetPageData = {
  body?: never;
  path: {
    siteId: string;
    pageId: string;
  };
  query?: never;
  url: '/sites/{siteId}/pages/{pageId}';
};

export type GetPageErrors = {
  /**
   * Default Response
   */
  400: Def2;
  /**
   * Default Response
   */
  401: Def3;
  /**
   * Default Response
   */
  404: Def4;
  /**
   * Default Response
   */
  409: Def5;
  /**
   * Default Response
   */
  429: Def6;
  /**
   * Default Response
   */
  500: Def7;
  /**
   * Default Response
   */
  '4XX': Def1;
};

export type GetPageError = GetPageErrors[keyof GetPageErrors];

export type GetPageResponses = {
  /**
   * Default Response
   */
  200: {
    id: string;
    name: string;
    slug: string;
    folderId: string | null;
    folderPath?: string;
    status: 'draft' | 'publish';
    head: string;
    scripts: string;
    seo: {
      title: string;
      description: string;
    };
    metaTags: Array<{
      field: string;
      value: string;
      content: string;
    }>;
    layout: {
      name: string | null;
    };
    bodyProperties: {
      id?: string;
      className?: string;
      [key: string]: string | undefined;
    };
    content: string;
    collectionProperties?: {
      name: string;
      groupBy: string | null;
      pageType: 'list' | 'detail';
      offset: number;
      limit: number;
      itemsPerPage: number | null;
      filterItems: Array<{
        fieldName: string;
        filterType: '<' | '>' | '<=' | '>=' | '==' | '!=';
        value?: string;
      }>;
      sortItems: Array<{
        fieldName: string;
        sortBy: 'asc' | 'desc';
      }>;
    };
    createdAt: string;
    updatedAt: string;
    deletedAt?: string;
    createdBy: string;
    updatedBy: string;
    deletedBy?: string;
  };
};

export type GetPageResponse = GetPageResponses[keyof GetPageResponses];

export type ListComponentsData = {
  body?: never;
  path: {
    /**
     * Unique identifier for the Site
     */
    siteId: string;
  };
  query?: never;
  url: '/sites/{siteId}/components';
};

export type ListComponentsErrors = {
  /**
   * Default Response
   */
  400: Def2;
  /**
   * Default Response
   */
  401: Def3;
  /**
   * Default Response
   */
  404: Def4;
  /**
   * Default Response
   */
  409: Def5;
  /**
   * Default Response
   */
  429: Def6;
  /**
   * Default Response
   */
  500: Def7;
  /**
   * Default Response
   */
  '4XX': Def1;
};

export type ListComponentsError = ListComponentsErrors[keyof ListComponentsErrors];

export type ListComponentsResponses = {
  /**
   * Default Response
   */
  200: {
    data: Array<{
      id: string;
      name: string;
      folderId: string | null;
      folderPath?: string;
      content: string;
      groups?: Array<{
        name: string;
        slug: string;
        nestProperties: boolean;
      }>;
      properties: Array<
        | {
            name: string;
            slug: string;
            type: 'PlainText';
            group?: string | null;
            editable: boolean;
            required: boolean;
            validations: {
              visualModes: Array<'content' | 'developer' | 'designer'>;
              singleLine: boolean;
            };
            defaultValue?: string;
          }
        | {
            name: string;
            slug: string;
            type: 'Option';
            group?: string | null;
            editable: boolean;
            required: boolean;
            validations: {
              visualModes: Array<'content' | 'developer' | 'designer'>;
              options: Array<string>;
            };
            defaultValue?: string;
          }
        | {
            name: string;
            slug: string;
            type: 'ComponentRef';
            group?: string | null;
            editable: boolean;
            required: boolean;
            validations: {
              visualModes: Array<'content' | 'developer' | 'designer'>;
              componentName: string;
            };
          }
        | {
            name: string;
            slug: string;
            type: 'Color';
            group?: string | null;
            editable: boolean;
            required: boolean;
            validations: {
              visualModes: Array<'content' | 'developer' | 'designer'>;
              utilityPropertyKey: string;
            };
            defaultValue?: string;
          }
        | {
            name: string;
            slug: string;
            type: 'RichText';
            group?: string | null;
            editable: boolean;
            required: boolean;
            validations: {
              visualModes: Array<'content' | 'developer' | 'designer'>;
            };
          }
        | {
            name: string;
            slug: string;
            type: 'Bool';
            group?: string | null;
            editable: boolean;
            required: boolean;
            validations: {
              visualModes: Array<'content' | 'developer' | 'designer'>;
            };
          }
        | {
            name: string;
            slug: string;
            type: 'Image';
            group?: string | null;
            editable: boolean;
            required: boolean;
            validations: {
              visualModes: Array<'content' | 'developer' | 'designer'>;
            };
            defaultValue?: string;
          }
        | {
            name: string;
            slug: string;
            type: 'Video';
            group?: string | null;
            editable: boolean;
            required: boolean;
            validations: {
              visualModes: Array<'content' | 'developer' | 'designer'>;
            };
            defaultValue?: string;
          }
        | {
            name: string;
            slug: string;
            type: 'Link';
            group?: string | null;
            editable: boolean;
            required: boolean;
            validations: {
              visualModes: Array<'content' | 'developer' | 'designer'>;
            };
            defaultValue?: string;
          }
        | {
            name: string;
            slug: string;
            type: 'ClassName';
            group?: string | null;
            editable: boolean;
            required: boolean;
            validations: {
              visualModes: Array<'content' | 'developer' | 'designer'>;
            };
            defaultValue?: string;
          }
      >;
      createdAt: string;
      updatedAt: string;
      deletedAt?: string;
      createdBy: string;
      updatedBy: string;
      deletedBy?: string;
    }>;
  };
};

export type ListComponentsResponse = ListComponentsResponses[keyof ListComponentsResponses];

export type GetComponentData = {
  body?: never;
  path: {
    /**
     * Unique identifier for the Site
     */
    siteId: string;
    /**
     * Unique identifier
     */
    componentId: string;
  };
  query?: never;
  url: '/sites/{siteId}/components/{componentId}';
};

export type GetComponentErrors = {
  /**
   * Default Response
   */
  400: Def2;
  /**
   * Default Response
   */
  401: Def3;
  /**
   * Default Response
   */
  404: Def4;
  /**
   * Default Response
   */
  409: Def5;
  /**
   * Default Response
   */
  429: Def6;
  /**
   * Default Response
   */
  500: Def7;
  /**
   * Default Response
   */
  '4XX': Def1;
};

export type GetComponentError = GetComponentErrors[keyof GetComponentErrors];

export type GetComponentResponses = {
  /**
   * Default Response
   */
  200: {
    id: string;
    name: string;
    folderId: string | null;
    folderPath?: string;
    content: string;
    groups?: Array<{
      name: string;
      slug: string;
      nestProperties: boolean;
    }>;
    properties: Array<
      | {
          name: string;
          slug: string;
          type: 'PlainText';
          group?: string | null;
          editable: boolean;
          required: boolean;
          validations: {
            visualModes: Array<'content' | 'developer' | 'designer'>;
            singleLine: boolean;
          };
          defaultValue?: string;
        }
      | {
          name: string;
          slug: string;
          type: 'Option';
          group?: string | null;
          editable: boolean;
          required: boolean;
          validations: {
            visualModes: Array<'content' | 'developer' | 'designer'>;
            options: Array<string>;
          };
          defaultValue?: string;
        }
      | {
          name: string;
          slug: string;
          type: 'ComponentRef';
          group?: string | null;
          editable: boolean;
          required: boolean;
          validations: {
            visualModes: Array<'content' | 'developer' | 'designer'>;
            componentName: string;
          };
        }
      | {
          name: string;
          slug: string;
          type: 'Color';
          group?: string | null;
          editable: boolean;
          required: boolean;
          validations: {
            visualModes: Array<'content' | 'developer' | 'designer'>;
            utilityPropertyKey: string;
          };
          defaultValue?: string;
        }
      | {
          name: string;
          slug: string;
          type: 'RichText';
          group?: string | null;
          editable: boolean;
          required: boolean;
          validations: {
            visualModes: Array<'content' | 'developer' | 'designer'>;
          };
        }
      | {
          name: string;
          slug: string;
          type: 'Bool';
          group?: string | null;
          editable: boolean;
          required: boolean;
          validations: {
            visualModes: Array<'content' | 'developer' | 'designer'>;
          };
        }
      | {
          name: string;
          slug: string;
          type: 'Image';
          group?: string | null;
          editable: boolean;
          required: boolean;
          validations: {
            visualModes: Array<'content' | 'developer' | 'designer'>;
          };
          defaultValue?: string;
        }
      | {
          name: string;
          slug: string;
          type: 'Video';
          group?: string | null;
          editable: boolean;
          required: boolean;
          validations: {
            visualModes: Array<'content' | 'developer' | 'designer'>;
          };
          defaultValue?: string;
        }
      | {
          name: string;
          slug: string;
          type: 'Link';
          group?: string | null;
          editable: boolean;
          required: boolean;
          validations: {
            visualModes: Array<'content' | 'developer' | 'designer'>;
          };
          defaultValue?: string;
        }
      | {
          name: string;
          slug: string;
          type: 'ClassName';
          group?: string | null;
          editable: boolean;
          required: boolean;
          validations: {
            visualModes: Array<'content' | 'developer' | 'designer'>;
          };
          defaultValue?: string;
        }
    >;
    createdAt: string;
    updatedAt: string;
    deletedAt?: string;
    createdBy: string;
    updatedBy: string;
    deletedBy?: string;
  };
};

export type GetComponentResponse = GetComponentResponses[keyof GetComponentResponses];

export type DeleteAssetData = {
  body?: never;
  path: {
    /**
     * Unique identifier
     */
    assetId: string;
  };
  query?: never;
  url: '/assets/{assetId}';
};

export type DeleteAssetErrors = {
  /**
   * Default Response
   */
  400: Def2;
  /**
   * Default Response
   */
  401: Def3;
  /**
   * Default Response
   */
  404: Def4;
  /**
   * Default Response
   */
  409: Def5;
  /**
   * Default Response
   */
  429: Def6;
  /**
   * Default Response
   */
  500: Def7;
  /**
   * Default Response
   */
  '4XX': Def1;
};

export type DeleteAssetError = DeleteAssetErrors[keyof DeleteAssetErrors];

export type DeleteAssetResponses = {
  /**
   * Successfully executed
   */
  204: void;
};

export type DeleteAssetResponse = DeleteAssetResponses[keyof DeleteAssetResponses];

export type GetAssetData = {
  body?: never;
  path: {
    /**
     * Unique identifier
     */
    assetId: string;
  };
  query?: never;
  url: '/assets/{assetId}';
};

export type GetAssetErrors = {
  /**
   * Default Response
   */
  400: Def2;
  /**
   * Default Response
   */
  401: Def3;
  /**
   * Default Response
   */
  404: Def4;
  /**
   * Default Response
   */
  409: Def5;
  /**
   * Default Response
   */
  429: Def6;
  /**
   * Default Response
   */
  500: Def7;
  /**
   * Default Response
   */
  '4XX': Def1;
};

export type GetAssetError = GetAssetErrors[keyof GetAssetErrors];

export type GetAssetResponses = {
  /**
   * Default Response
   */
  200: {
    id: string;
    fileName: string;
    fileHash: string;
    folderPath?: string;
    hostedUrl: string;
    createdAt: string;
    updatedAt: string;
    width?: number;
    height?: number;
    fileSize?: number;
  };
};

export type GetAssetResponse = GetAssetResponses[keyof GetAssetResponses];

export type UpdateAssetData = {
  body: {
    fileName: string;
    folderPath?: string;
  };
  path: {
    /**
     * Unique identifier
     */
    assetId: string;
  };
  query?: never;
  url: '/assets/{assetId}';
};

export type UpdateAssetErrors = {
  /**
   * Default Response
   */
  400: Def2;
  /**
   * Default Response
   */
  401: Def3;
  /**
   * Default Response
   */
  404: Def4;
  /**
   * Default Response
   */
  409: Def5;
  /**
   * Default Response
   */
  429: Def6;
  /**
   * Default Response
   */
  500: Def7;
  /**
   * Default Response
   */
  '4XX': Def1;
};

export type UpdateAssetError = UpdateAssetErrors[keyof UpdateAssetErrors];

export type UpdateAssetResponses = {
  /**
   * Default Response
   */
  200: {
    id: string;
    fileName: string;
    fileHash: string;
    folderPath?: string;
    hostedUrl: string;
    createdAt: string;
    updatedAt: string;
    width?: number;
    height?: number;
    fileSize?: number;
  };
};

export type UpdateAssetResponse = UpdateAssetResponses[keyof UpdateAssetResponses];

export type ListAssetsData = {
  body?: never;
  path: {
    /**
     * Unique identifier for the Workspace
     */
    workspaceId: string;
  };
  query?: {
    limit?: number;
    offset?: number;
    updatedAt?: string;
  };
  url: '/workspaces/{workspaceId}/assets';
};

export type ListAssetsErrors = {
  /**
   * Default Response
   */
  400: Def2;
  /**
   * Default Response
   */
  401: Def3;
  /**
   * Default Response
   */
  404: Def4;
  /**
   * Default Response
   */
  409: Def5;
  /**
   * Default Response
   */
  429: Def6;
  /**
   * Default Response
   */
  500: Def7;
  /**
   * Default Response
   */
  '4XX': Def1;
};

export type ListAssetsError = ListAssetsErrors[keyof ListAssetsErrors];

export type ListAssetsResponses = {
  /**
   * Default Response
   */
  200: {
    data: Array<{
      id: string;
      fileName: string;
      fileHash: string;
      folderPath?: string;
      hostedUrl: string;
      createdAt: string;
      updatedAt: string;
      width?: number;
      height?: number;
      fileSize?: number;
    }>;
    limit?: number;
    offset?: number;
    total?: number;
  };
};

export type ListAssetsResponse = ListAssetsResponses[keyof ListAssetsResponses];

export type CreateAssetData = {
  body: {
    file: {
      [key: string]: unknown;
    };
    fileName: string;
    folderPath?: string;
  };
  path: {
    /**
     * Unique identifier for the Workspace
     */
    workspaceId: string;
  };
  query?: never;
  url: '/workspaces/{workspaceId}/assets';
};

export type CreateAssetErrors = {
  /**
   * Default Response
   */
  400: Def2;
  /**
   * Default Response
   */
  401: Def3;
  /**
   * Default Response
   */
  404: Def4;
  /**
   * Default Response
   */
  409: Def5;
  /**
   * Default Response
   */
  429: Def6;
  /**
   * Default Response
   */
  500: Def7;
  /**
   * Default Response
   */
  '4XX': Def1;
};

export type CreateAssetError = CreateAssetErrors[keyof CreateAssetErrors];

export type CreateAssetResponses = {
  /**
   * Default Response
   */
  200: {
    id: string;
    fileName: string;
    fileHash: string;
    folderPath?: string;
    hostedUrl: string;
    createdAt: string;
    updatedAt: string;
    width?: number;
    height?: number;
    fileSize?: number;
  };
};

export type CreateAssetResponse = CreateAssetResponses[keyof CreateAssetResponses];

export type ListFormsData = {
  body?: never;
  path: {
    /**
     * Unique identifier for the Site
     */
    siteId: string;
  };
  query?: never;
  url: '/sites/{siteId}/forms';
};

export type ListFormsErrors = {
  /**
   * Default Response
   */
  400: Def2;
  /**
   * Default Response
   */
  401: Def3;
  /**
   * Default Response
   */
  404: Def4;
  /**
   * Default Response
   */
  409: Def5;
  /**
   * Default Response
   */
  429: Def6;
  /**
   * Default Response
   */
  500: Def7;
  /**
   * Default Response
   */
  '4XX': Def1;
};

export type ListFormsError = ListFormsErrors[keyof ListFormsErrors];

export type ListFormsResponses = {
  /**
   * Default Response
   */
  200: {
    data: Array<{
      /**
       * Unique identifier
       */
      id?: string;
      /**
       * Unique identifier
       */
      siteId?: string;
      name?: string;
      /**
       * Date and time in ISO 8601 format
       */
      createdAt?: string;
      /**
       * Date and time in ISO 8601 format
       */
      updatedAt?: string;
    }>;
  };
};

export type ListFormsResponse = ListFormsResponses[keyof ListFormsResponses];

export type GetFormData = {
  body?: never;
  path: {
    /**
     * Unique identifier
     */
    formId: string;
  };
  query?: never;
  url: '/forms/{formId}';
};

export type GetFormErrors = {
  /**
   * Default Response
   */
  400: Def2;
  /**
   * Default Response
   */
  401: Def3;
  /**
   * Default Response
   */
  404: Def4;
  /**
   * Default Response
   */
  409: Def5;
  /**
   * Default Response
   */
  429: Def6;
  /**
   * Default Response
   */
  500: Def7;
  /**
   * Default Response
   */
  '4XX': Def1;
};

export type GetFormError = GetFormErrors[keyof GetFormErrors];

export type GetFormResponses = {
  /**
   * Default Response
   */
  200: {
    /**
     * Unique identifier
     */
    id?: string;
    /**
     * Unique identifier
     */
    siteId?: string;
    name?: string;
    /**
     * Date and time in ISO 8601 format
     */
    createdAt?: string;
    /**
     * Date and time in ISO 8601 format
     */
    updatedAt?: string;
  };
};

export type GetFormResponse = GetFormResponses[keyof GetFormResponses];

export type ListFormSubmissionsData = {
  body?: never;
  path: {
    /**
     * Unique identifier
     */
    formId: string;
  };
  query?: never;
  url: '/forms/{formId}/submissions';
};

export type ListFormSubmissionsErrors = {
  /**
   * Default Response
   */
  400: Def2;
  /**
   * Default Response
   */
  401: Def3;
  /**
   * Default Response
   */
  404: Def4;
  /**
   * Default Response
   */
  409: Def5;
  /**
   * Default Response
   */
  429: Def6;
  /**
   * Default Response
   */
  500: Def7;
  /**
   * Default Response
   */
  '4XX': Def1;
};

export type ListFormSubmissionsError = ListFormSubmissionsErrors[keyof ListFormSubmissionsErrors];

export type ListFormSubmissionsResponses = {
  /**
   * Default Response
   */
  200: {
    data: Array<{
      /**
       * Unique identifier
       */
      id: string;
      /**
       * Unique identifier
       */
      formId: string;
      /**
       * Unique identifier
       */
      siteId: string;
      createdAt: string;
      formResponse: {
        [key: string]: unknown;
      };
    }>;
  };
};

export type ListFormSubmissionsResponse = ListFormSubmissionsResponses[keyof ListFormSubmissionsResponses];

export type GetFormSubmissionData = {
  body?: never;
  path: {
    /**
     * Unique identifier
     */
    formSubmissionId: string;
  };
  query?: never;
  url: '/form_submissions/{formSubmissionId}';
};

export type GetFormSubmissionErrors = {
  /**
   * Default Response
   */
  400: Def2;
  /**
   * Default Response
   */
  401: Def3;
  /**
   * Default Response
   */
  404: Def4;
  /**
   * Default Response
   */
  409: Def5;
  /**
   * Default Response
   */
  429: Def6;
  /**
   * Default Response
   */
  500: Def7;
  /**
   * Default Response
   */
  '4XX': Def1;
};

export type GetFormSubmissionError = GetFormSubmissionErrors[keyof GetFormSubmissionErrors];

export type GetFormSubmissionResponses = {
  /**
   * Default Response
   */
  200: {
    /**
     * Unique identifier
     */
    id: string;
    /**
     * Unique identifier
     */
    formId: string;
    /**
     * Unique identifier
     */
    siteId: string;
    createdAt: string;
    formResponse: {
      [key: string]: unknown;
    };
  };
};

export type GetFormSubmissionResponse = GetFormSubmissionResponses[keyof GetFormSubmissionResponses];

export type ListCollectionsData = {
  body?: never;
  path: {
    /**
     * Unique identifier for the Site
     */
    siteId: string;
  };
  query?: never;
  url: '/sites/{siteId}/collections';
};

export type ListCollectionsErrors = {
  /**
   * Default Response
   */
  400: Def2;
  /**
   * Default Response
   */
  401: Def3;
  /**
   * Default Response
   */
  404: Def4;
  /**
   * Default Response
   */
  409: Def5;
  /**
   * Default Response
   */
  429: Def6;
  /**
   * Default Response
   */
  500: Def7;
  /**
   * Default Response
   */
  '4XX': Def1;
};

export type ListCollectionsError = ListCollectionsErrors[keyof ListCollectionsErrors];

export type ListCollectionsResponses = {
  /**
   * Default Response
   */
  200: {
    data: Array<{
      id?: string;
      name?: string;
      singularName?: string;
      slug?: string;
      createdAt?: string;
      publishedAt?: string;
      updatedAt?: string;
    }>;
  };
};

export type ListCollectionsResponse = ListCollectionsResponses[keyof ListCollectionsResponses];

export type GetCollectionData = {
  body?: never;
  path: {
    /**
     * Unique identifier
     */
    collectionId: string;
  };
  query?: never;
  url: '/collections/{collectionId}';
};

export type GetCollectionErrors = {
  /**
   * Default Response
   */
  400: Def2;
  /**
   * Default Response
   */
  401: Def3;
  /**
   * Default Response
   */
  404: Def4;
  /**
   * Default Response
   */
  409: Def5;
  /**
   * Default Response
   */
  429: Def6;
  /**
   * Default Response
   */
  500: Def7;
  /**
   * Default Response
   */
  '4XX': Def1;
};

export type GetCollectionError = GetCollectionErrors[keyof GetCollectionErrors];

export type GetCollectionResponses = {
  /**
   * Default Response
   */
  200: {
    /**
     * Unique identifier
     */
    id?: string;
    name?: string;
    slug?: string;
    singularName?: string;
    /**
     * Date and time in ISO 8601 format
     */
    createdAt?: string;
    /**
     * Date and time in ISO 8601 format
     */
    publishedAt?: string;
    /**
     * Date and time in ISO 8601 format
     */
    updatedAt?: string;
    fields?: Array<{
      name: string;
      slug: string;
      type: string;
      editable?: boolean;
      required?: boolean;
      validations?: {
        collectionId?: string;
      };
    }>;
  };
};

export type GetCollectionResponse = GetCollectionResponses[keyof GetCollectionResponses];

export type DeleteItemsData = {
  body: {
    itemIds: Array<string>;
  };
  path: {
    /**
     * Unique identifier
     */
    collectionId: string;
  };
  query?: never;
  url: '/collections/{collectionId}/items';
};

export type DeleteItemsErrors = {
  /**
   * Default Response
   */
  400: Def2;
  /**
   * Default Response
   */
  401: Def3;
  /**
   * Default Response
   */
  404: Def4;
  /**
   * Default Response
   */
  409: Def5;
  /**
   * Default Response
   */
  429: Def6;
  /**
   * Default Response
   */
  500: Def7;
  /**
   * Default Response
   */
  '4XX': Def1;
};

export type DeleteItemsError = DeleteItemsErrors[keyof DeleteItemsErrors];

export type DeleteItemsResponses = {
  /**
   * Successfully executed
   */
  204: void;
};

export type DeleteItemsResponse = DeleteItemsResponses[keyof DeleteItemsResponses];

export type ListItemsData = {
  body?: never;
  path: {
    /**
     * Unique identifier
     */
    collectionId: string;
  };
  query?: {
    limit?: number;
    offset?: number;
    updatedAt?: string;
    order?: 'updatedAt' | 'updatedAt.desc' | 'updatedAt.asc';
  };
  url: '/collections/{collectionId}/items';
};

export type ListItemsErrors = {
  /**
   * Default Response
   */
  400: Def2;
  /**
   * Default Response
   */
  401: Def3;
  /**
   * Default Response
   */
  404: Def4;
  /**
   * Default Response
   */
  409: Def5;
  /**
   * Default Response
   */
  429: Def6;
  /**
   * Default Response
   */
  500: Def7;
  /**
   * Default Response
   */
  '4XX': Def1;
};

export type ListItemsError = ListItemsErrors[keyof ListItemsErrors];

export type ListItemsResponses = {
  /**
   * Default Response
   */
  200: {
    data: Array<{
      /**
       * Unique identifier
       */
      id: string;
      createdAt: string;
      updatedAt: string;
      fieldData: {
        name?: string;
        slug?: string;
        [key: string]: unknown | string | undefined;
      };
    }>;
    limit?: number;
    offset?: number;
    total?: number;
  };
};

export type ListItemsResponse = ListItemsResponses[keyof ListItemsResponses];

export type CreateItemData = {
  body: {
    fieldData: {
      name: string;
      slug: string;
      [key: string]: unknown | string;
    };
  };
  path: {
    /**
     * Unique identifier
     */
    collectionId: string;
  };
  query?: never;
  url: '/collections/{collectionId}/items';
};

export type CreateItemErrors = {
  /**
   * Default Response
   */
  400: Def2;
  /**
   * Default Response
   */
  401: Def3;
  /**
   * Default Response
   */
  404: Def4;
  /**
   * Default Response
   */
  409: Def5;
  /**
   * Default Response
   */
  429: Def6;
  /**
   * Default Response
   */
  500: Def7;
  /**
   * Default Response
   */
  '4XX': Def1;
};

export type CreateItemError = CreateItemErrors[keyof CreateItemErrors];

export type CreateItemResponses = {
  /**
   * Default Response
   */
  200: {
    /**
     * Unique identifier
     */
    id: string;
    createdAt: string;
    updatedAt: string;
    fieldData: {
      name?: string;
      slug?: string;
      [key: string]: unknown | string | undefined;
    };
  };
};

export type CreateItemResponse = CreateItemResponses[keyof CreateItemResponses];

export type GetItemData = {
  body?: never;
  path: {
    /**
     * Unique identifier for the Collection
     */
    collectionId: string;
    /**
     * Unique identifier for the Item
     */
    itemId: string;
  };
  query?: never;
  url: '/collections/{collectionId}/items/{itemId}';
};

export type GetItemErrors = {
  /**
   * Default Response
   */
  400: Def2;
  /**
   * Default Response
   */
  401: Def3;
  /**
   * Default Response
   */
  404: Def4;
  /**
   * Default Response
   */
  409: Def5;
  /**
   * Default Response
   */
  429: Def6;
  /**
   * Default Response
   */
  500: Def7;
  /**
   * Default Response
   */
  '4XX': Def1;
};

export type GetItemError = GetItemErrors[keyof GetItemErrors];

export type GetItemResponses = {
  /**
   * Default Response
   */
  200: {
    /**
     * Unique identifier
     */
    id: string;
    createdAt: string;
    updatedAt: string;
    fieldData: {
      name?: string;
      slug?: string;
      [key: string]: unknown | string | undefined;
    };
  };
};

export type GetItemResponse = GetItemResponses[keyof GetItemResponses];

export type UpdateItemData = {
  body: {
    fieldData: {
      name?: string;
      slug?: string;
      [key: string]: unknown | string | undefined;
    };
  };
  path: {
    /**
     * Unique identifier
     */
    collectionId: string;
    /**
     * Unique identifier
     */
    itemId: string;
  };
  query?: never;
  url: '/collections/{collectionId}/items/{itemId}';
};

export type UpdateItemErrors = {
  /**
   * Default Response
   */
  400: Def2;
  /**
   * Default Response
   */
  401: Def3;
  /**
   * Default Response
   */
  404: Def4;
  /**
   * Default Response
   */
  409: Def5;
  /**
   * Default Response
   */
  429: Def6;
  /**
   * Default Response
   */
  500: Def7;
  /**
   * Default Response
   */
  '4XX': Def1;
};

export type UpdateItemError = UpdateItemErrors[keyof UpdateItemErrors];

export type UpdateItemResponses = {
  /**
   * Default Response
   */
  200: {
    /**
     * Unique identifier
     */
    id: string;
    createdAt: string;
    updatedAt: string;
    fieldData: {
      name?: string;
      slug?: string;
      [key: string]: unknown | string | undefined;
    };
  };
};

export type UpdateItemResponse = UpdateItemResponses[keyof UpdateItemResponses];

export type ListPublicFilesData = {
  body?: never;
  path: {
    siteId: string;
  };
  query?: never;
  url: '/sites/{siteId}/public_files';
};

export type ListPublicFilesErrors = {
  /**
   * Default Response
   */
  400: Def2;
  /**
   * Default Response
   */
  401: Def3;
  /**
   * Default Response
   */
  404: Def4;
  /**
   * Default Response
   */
  409: Def5;
  /**
   * Default Response
   */
  429: Def6;
  /**
   * Default Response
   */
  500: Def7;
  /**
   * Default Response
   */
  '4XX': Def1;
};

export type ListPublicFilesError = ListPublicFilesErrors[keyof ListPublicFilesErrors];

export type ListPublicFilesResponses = {
  /**
   * Default Response
   */
  200: {
    data: Array<{
      siteId: string;
      content: string;
      contentType: string | null;
      updatedAt: string;
      path:
        | 'robots.txt'
        | '.well-known/apple-app-site-association'
        | '.well-known/assetlinks.json'
        | 'llms.txt'
        | 'llms-full.txt';
    }>;
  };
};

export type ListPublicFilesResponse = ListPublicFilesResponses[keyof ListPublicFilesResponses];

export type DeletePublicFileData = {
  body?: never;
  path: {
    siteId: string;
    path:
      | 'robots.txt'
      | '.well-known/apple-app-site-association'
      | '.well-known/assetlinks.json'
      | 'llms.txt'
      | 'llms-full.txt';
  };
  query?: never;
  url: '/sites/{siteId}/public_files/{path}';
};

export type DeletePublicFileErrors = {
  /**
   * Default Response
   */
  400: Def2;
  /**
   * Default Response
   */
  401: Def3;
  /**
   * Default Response
   */
  404: Def4;
  /**
   * Default Response
   */
  409: Def5;
  /**
   * Default Response
   */
  429: Def6;
  /**
   * Default Response
   */
  500: Def7;
  /**
   * Default Response
   */
  '4XX': Def1;
};

export type DeletePublicFileError = DeletePublicFileErrors[keyof DeletePublicFileErrors];

export type DeletePublicFileResponses = {
  /**
   * Default Response
   */
  200: {
    siteId: string;
    content: string;
    contentType: string | null;
    updatedAt: string;
    path:
      | 'robots.txt'
      | '.well-known/apple-app-site-association'
      | '.well-known/assetlinks.json'
      | 'llms.txt'
      | 'llms-full.txt';
  };
};

export type DeletePublicFileResponse = DeletePublicFileResponses[keyof DeletePublicFileResponses];

export type GetPublicFileData = {
  body?: never;
  path: {
    siteId: string;
    path:
      | 'robots.txt'
      | '.well-known/apple-app-site-association'
      | '.well-known/assetlinks.json'
      | 'llms.txt'
      | 'llms-full.txt';
  };
  query?: never;
  url: '/sites/{siteId}/public_files/{path}';
};

export type GetPublicFileErrors = {
  /**
   * Default Response
   */
  400: Def2;
  /**
   * Default Response
   */
  401: Def3;
  /**
   * Default Response
   */
  404: Def4;
  /**
   * Default Response
   */
  409: Def5;
  /**
   * Default Response
   */
  429: Def6;
  /**
   * Default Response
   */
  500: Def7;
  /**
   * Default Response
   */
  '4XX': Def1;
};

export type GetPublicFileError = GetPublicFileErrors[keyof GetPublicFileErrors];

export type GetPublicFileResponses = {
  /**
   * Default Response
   */
  200: {
    siteId: string;
    content: string;
    contentType: string | null;
    updatedAt: string;
    path:
      | 'robots.txt'
      | '.well-known/apple-app-site-association'
      | '.well-known/assetlinks.json'
      | 'llms.txt'
      | 'llms-full.txt';
  };
};

export type GetPublicFileResponse = GetPublicFileResponses[keyof GetPublicFileResponses];

export type UpdatePublicFileData = {
  body: {
    content: string;
  };
  path: {
    siteId: string;
    path:
      | 'robots.txt'
      | '.well-known/apple-app-site-association'
      | '.well-known/assetlinks.json'
      | 'llms.txt'
      | 'llms-full.txt';
  };
  query?: never;
  url: '/sites/{siteId}/public_files/{path}';
};

export type UpdatePublicFileErrors = {
  /**
   * Default Response
   */
  400: Def2;
  /**
   * Default Response
   */
  401: Def3;
  /**
   * Default Response
   */
  404: Def4;
  /**
   * Default Response
   */
  409: Def5;
  /**
   * Default Response
   */
  429: Def6;
  /**
   * Default Response
   */
  500: Def7;
  /**
   * Default Response
   */
  '4XX': Def1;
};

export type UpdatePublicFileError = UpdatePublicFileErrors[keyof UpdatePublicFileErrors];

export type UpdatePublicFileResponses = {
  /**
   * Default Response
   */
  200: {
    siteId: string;
    content: string;
    contentType: string | null;
    updatedAt: string;
    path:
      | 'robots.txt'
      | '.well-known/apple-app-site-association'
      | '.well-known/assetlinks.json'
      | 'llms.txt'
      | 'llms-full.txt';
  };
};

export type UpdatePublicFileResponse = UpdatePublicFileResponses[keyof UpdatePublicFileResponses];

export type ListRedirectsData = {
  body?: never;
  path: {
    siteId: string;
  };
  query?: never;
  url: '/sites/{siteId}/redirects';
};

export type ListRedirectsErrors = {
  /**
   * Default Response
   */
  400: Def2;
  /**
   * Default Response
   */
  401: Def3;
  /**
   * Default Response
   */
  404: Def4;
  /**
   * Default Response
   */
  409: Def5;
  /**
   * Default Response
   */
  429: Def6;
  /**
   * Default Response
   */
  500: Def7;
  /**
   * Default Response
   */
  '4XX': Def1;
};

export type ListRedirectsError = ListRedirectsErrors[keyof ListRedirectsErrors];

export type ListRedirectsResponses = {
  /**
   * Default Response
   */
  200: {
    data: Array<{
      fromUrl: string;
      toUrl: string;
      redirectType: 301 | 302;
    }>;
  };
};

export type ListRedirectsResponse = ListRedirectsResponses[keyof ListRedirectsResponses];

export type ListWebhooksData = {
  body?: never;
  path: {
    siteId: string;
  };
  query?: never;
  url: '/sites/{siteId}/webhooks';
};

export type ListWebhooksErrors = {
  /**
   * Default Response
   */
  400: Def2;
  /**
   * Default Response
   */
  401: Def3;
  /**
   * Default Response
   */
  404: Def4;
  /**
   * Default Response
   */
  409: Def5;
  /**
   * Default Response
   */
  429: Def6;
  /**
   * Default Response
   */
  500: Def7;
  /**
   * Default Response
   */
  '4XX': Def1;
};

export type ListWebhooksError = ListWebhooksErrors[keyof ListWebhooksErrors];

export type ListWebhooksResponses = {
  /**
   * Default Response
   */
  200: {
    data: Array<{
      id: string;
      siteId: string;
      url: string;
      filters: {
        formId?: string;
      };
      createdAt: string;
      disabledAt: string | null;
      lastTriggeredAt: string | null;
      eventType:
        | 'form.submission'
        | 'site.published'
        | 'collection.item.created'
        | 'collection.item.updated'
        | 'collection.items.deleted';
    }>;
  };
};

export type ListWebhooksResponse = ListWebhooksResponses[keyof ListWebhooksResponses];

export type CreateWebhookData = {
  body: {
    eventType:
      | 'form.submission'
      | 'site.published'
      | 'collection.item.created'
      | 'collection.item.updated'
      | 'collection.items.deleted';
    url: string;
    filters?: {
      formId?: string;
    };
  };
  path: {
    /**
     * Unique identifier for the Site
     */
    siteId: string;
  };
  query?: never;
  url: '/sites/{siteId}/webhooks';
};

export type CreateWebhookErrors = {
  /**
   * Default Response
   */
  400: Def2;
  /**
   * Default Response
   */
  401: Def3;
  /**
   * Default Response
   */
  404: Def4;
  /**
   * Default Response
   */
  409: Def5;
  /**
   * Default Response
   */
  429: Def6;
  /**
   * Default Response
   */
  500: Def7;
  /**
   * Default Response
   */
  '4XX': Def1;
};

export type CreateWebhookError = CreateWebhookErrors[keyof CreateWebhookErrors];

export type CreateWebhookResponses = {
  /**
   * Default Response
   */
  200: {
    id: string;
    siteId: string;
    url: string;
    filters: {
      formId?: string;
    };
    createdAt: string;
    disabledAt: string | null;
    lastTriggeredAt: string | null;
    eventType:
      | 'form.submission'
      | 'site.published'
      | 'collection.item.created'
      | 'collection.item.updated'
      | 'collection.items.deleted';
  };
};

export type CreateWebhookResponse = CreateWebhookResponses[keyof CreateWebhookResponses];

export type DeleteWebhookData = {
  body?: never;
  path: {
    /**
     * Unique identifier
     */
    webhookId: string;
  };
  query?: never;
  url: '/webhooks/{webhookId}';
};

export type DeleteWebhookErrors = {
  /**
   * Default Response
   */
  400: Def2;
  /**
   * Default Response
   */
  401: Def3;
  /**
   * Default Response
   */
  404: Def4;
  /**
   * Default Response
   */
  409: Def5;
  /**
   * Default Response
   */
  429: Def6;
  /**
   * Default Response
   */
  500: Def7;
  /**
   * Default Response
   */
  '4XX': Def1;
};

export type DeleteWebhookError = DeleteWebhookErrors[keyof DeleteWebhookErrors];

export type DeleteWebhookResponses = {
  /**
   * Successfully executed
   */
  204: void;
};

export type DeleteWebhookResponse = DeleteWebhookResponses[keyof DeleteWebhookResponses];

export type GetWebhookData = {
  body?: never;
  path: {
    /**
     * Unique identifier
     */
    webhookId: string;
  };
  query?: never;
  url: '/webhooks/{webhookId}';
};

export type GetWebhookErrors = {
  /**
   * Default Response
   */
  400: Def2;
  /**
   * Default Response
   */
  401: Def3;
  /**
   * Default Response
   */
  404: Def4;
  /**
   * Default Response
   */
  409: Def5;
  /**
   * Default Response
   */
  429: Def6;
  /**
   * Default Response
   */
  500: Def7;
  /**
   * Default Response
   */
  '4XX': Def1;
};

export type GetWebhookError = GetWebhookErrors[keyof GetWebhookErrors];

export type GetWebhookResponses = {
  /**
   * Default Response
   */
  200: {
    id: string;
    siteId: string;
    url: string;
    filters: {
      formId?: string;
    };
    createdAt: string;
    disabledAt: string | null;
    lastTriggeredAt: string | null;
    eventType:
      | 'form.submission'
      | 'site.published'
      | 'collection.item.created'
      | 'collection.item.updated'
      | 'collection.items.deleted';
  };
};

export type GetWebhookResponse = GetWebhookResponses[keyof GetWebhookResponses];
